# Numpy
- Scientific computation
- Supports for arrays and matrices 

In [4]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 7.2 MB/s eta 0:00:00a 0:00:01


In [5]:
import numpy as np

In [6]:
# create array using numpy
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [7]:
# reshaping to 2-D array
arr1.reshape(1,4) ## 1 row 4 columns
arr1
arr1.shape

(4,)

In [8]:
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print("shape : ",arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
shape :  (2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
arr = np.array([[1,2,3], [4,5,6]])
arr

print("array : ",arr)
print("Shape : ", arr.shape)
print("number of dimension : ", arr.ndim)
print("size (number of elements) : ", arr.size)
print("data type : ", arr.dtype)
print("item size (in bytes) : ", arr.itemsize)

array :  [[1 2 3]
 [4 5 6]]
Shape :  (2, 3)
number of dimension :  2
size (number of elements) :  6
data type :  int64
item size (in bytes) :  8


In [18]:
# numpy vectorized operations 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])

# element wise operations  
print("addition : ", arr1+arr2)
print("subtraction : ",arr1-arr2)
print("multiplication : ",arr1*arr2)
print("division : ",arr1 / arr2)

addition :  [11 22 33 44 55 66]
subtraction :  [ -9 -18 -27 -36 -45 -54]
multiplication :  [ 10  40  90 160 250 360]
division :  [0.1 0.1 0.1 0.1 0.1 0.1]


In [24]:
## Universal functions 
arr = np.array([2,3,4,5,6,7])

print("square root : ",np.sqrt(arr)) # square root
print("exponential : ", np.exp(arr)) # exponential 
print("sin : ", np.sin(arr)) # sine
print("log : ", np.log(arr)) # natural log

square root :  [1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131]
exponential :  [   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843]
sin :  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
log :  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015]


In [ ]:
## array slicing and indexing 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("array : ", arr)

print("first element : ",arr[0][0])
print("first row : ",arr[0]) 
print("after first all rows  : ", arr[1:])

print(arr[0:2,2:])
print(arr[2][0:3])

array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
first element :  1
first row :  [1 2 3 4 5]
after first all rows  :  [[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 3  4  5]
 [ 8  9 10]]
[11 12 13]


In [41]:
# modify array elements 
arr[0][0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [42]:
## Statistical operations 
data = np.array([1,2,3,4,5,6,7,8,9])

print("mean : ", np.mean(data))
print("median : ", np.median(data))
print("standard deviation : ", np.std(data))
print("variance : ", np.var(data))

mean :  5.0
median :  5.0
standard deviation :  2.581988897471611
variance :  6.666666666666667


In [ ]:
## Data normalizations 
# - Converting a data in a way such that mean is 0 and standard deviation is 1

data = np.array([1,2,3,4,5,6])

# calcuate the means and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

# normalize the data 
normalize_data = (data - mean) / std_dev
print("normalized_data : ", normalize_data)

normalized_data :  [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [46]:
## logical operations 
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data > 5]

data[(data > 5) & (data <=8)]

array([6, 7, 8])